IMAGE title_1_img    "images/Title_mid_1.bmp"            NONE
IMAGE title_2_img    "images/Title_mid_2.bmp"            NONE
IMAGE brd_end_1_img  "images/BoardEnding_mid_1.bmp"      AUTO
IMAGE brd_end_2_img  "images/BoardEnding_mid_2.bmp"      AUTO
IMAGE bns_end_1_img  "images/BonusEnd_mid_1.bmp"         AUTO
IMAGE bns_end_2_img  "images/BonusEnd_mid_2.bmp"         AUTO
IMAGE nothing_img    "images/nothing_low.bmp"            AUTO
IMAGE bns_begin_1_img  "images/BonusBegin_mid_1.bmp"         AUTO
IMAGE bns_begin_2_img  "images/BonusBegin_mid_2.bmp"         AUTO